version: '3'

name: lightforum-prod
services:
  lf-db:
    image: postgres:15.3
    volumes:
      - ./backend/database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lf-db-prod
    ports:
      - 5432:5432
  lf-backend-prod:
    image: node:20-alpine3.16
    depends_on:
      - lf-db
    volumes:
      - ./backend/:/usr/src/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lf-db-prod
      - POSTGRES_PORT=5432
      - POSTGRES_CONTAINER=lf-db
    container_name: lf-backend-prod
    command: >
        sh -c "cd /usr/src/app && npm install && npm run build && npm start"
  lf-frontend-prod:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.build
    ports:
      - 80:80
    container_name: lf-frontend-prod 
