name: lightforum-dev
services:
  lf-db-dev:
    image: postgres:15.3
    volumes:
      - ./backend/database-dev/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lf-db-dev
    ports:
      - 5432:5432
  lf-backend-dev:
    image: node:20-alpine3.16
    depends_on:
      - lf-db-dev
    volumes:
      - ./backend/:/usr/src/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lf-db-dev
      - POSTGRES_PORT=5432
      - POSTGRES_CONTAINER=lf-db-dev
    container_name: lf-backend-dev
    ports:
      - 3001:3001
    command: >
        sh -c "cd /usr/src/app && npm install && npm run dev"
  lf-frontend-dev:
    image: node:20-alpine3.16
    volumes:
      - ./frontend/:/usr/src/app
    container_name: lf-frontend-dev
    ports:
      - 80:5173
    command: >
        sh -c "cd /usr/src/app && npm install && npm run dev -- --host"
  