name: lightforum-prod
services:
  lf-backend-prod:
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001 # only for testing, remove this later!
    container_name: lf-backend-prod
    command: >
        sh -c "cd /usr/src/app && npm install && npm run build && npm start"
  lf-frontend-prod:
    image: nginx:1.20.1
    build:
      context: ./frontend/
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: lf-frontend-prod
    
