name: lightforum-dev
services:
  lf-backend-dev:
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    container_name: lf-backend-dev
    ports:
      - 3001:3001
    command: >
        sh -c "cd /usr/src/app && npm install && npm run dev"
  lf-frontend-dev:
    image: node:20-alpine3.16
    volumes:
      - ./frontend/:/usr/src/app
    container_name: lf-frontend-dev
    ports:
      - 80:5173
    command: >
        sh -c "cd /usr/src/app && npm install && npm run dev -- --host"
