name: 'Deploy to server'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ !contains(github.event.head_commit.message, '#nodeploy') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.VPS_SERVER_FOLDER }}
            git pull
            ./add_last_updated
            docker compose build
            docker compose up -d
